#[path = "auth-provider.command.rs"]
pub mod auth_provider_command;
#[path = "chat-account.command.rs"]
pub mod chat_account_command;
#[path = "chat-channel.command.rs"]
pub mod chat_channel_command;
#[path = "chat.command.rs"]
pub mod chat_command;
#[path = "chat-message.command.rs"]
pub mod chat_message_command;
#[path = "crud_command.rs"]
pub mod crud_command;
#[path = "crud.macro.rs"]
pub mod crud_macro;
#[path = "custom-emote.command.rs"]
pub mod custom_emote_command;
#[path = "dashboard-preferences.command.rs"]
pub mod dashboard_preferences_command;
#[path = "icons.command.rs"]
pub mod icons_command;
#[path = "macros.rs"]
pub mod macros;
#[path = "overlay.command.rs"]
pub mod overlay_command;
#[path = "storage.command.rs"]
pub mod storage_command;
#[path = "update.command.rs"]
pub mod update_command;
