import { ChatChannel, ChatMessage, WidgetConfig } from "@models/chat.model";
import { createMessageActionState } from "@helpers/chat.helper";

export const mockChannels: ChatChannel[] = [
  {
    id: "ch-twitch-1",
    platform: "twitch",
    channelId: "twitch-unichat-live",
    channelName: "unichat_live",
    isAuthorized: true,
    isVisible: true,
    addedAt: new Date().toISOString(),
  },
  {
    id: "ch-twitch-2",
    platform: "twitch",
    channelId: "twitch-shroud",
    channelName: "shroud",
    isAuthorized: false,
    isVisible: true,
    addedAt: new Date().toISOString(),
  },
  {
    id: "ch-kick-1",
    platform: "kick",
    channelId: "kick-xqc",
    channelName: "xQc",
    isAuthorized: false,
    isVisible: true,
    addedAt: new Date().toISOString(),
  },
  {
    id: "ch-youtube-1",
    platform: "youtube",
    channelId: "youtube-gamespot",
    channelName: "GameSpot",
    isAuthorized: false,
    isVisible: true,
    addedAt: new Date().toISOString(),
  },
];

export const mockMessages: ChatMessage[] = [
  {
    id: "m-001",
    platform: "twitch",
    sourceMessageId: "tw-1001",
    sourceChannelId: "twitch-unichat-live",
    sourceUserId: "user-lumapilot",
    author: "LumaPilot",
    text: "Main feed looks good. I need a single place to reply without losing platform context.",
    timestamp: "2026-03-23T12:09:00.000Z",
    badges: ["mod", "supporter"],
    isSupporter: true,
    isOutgoing: false,
    isDeleted: false,
    canRenderInOverlay: true,
    actions: {
      reply: createMessageActionState("reply", "available"),
      delete: createMessageActionState("delete", "available"),
    },
    rawPayload: {
      providerEvent: "privmsg",
      providerChannelId: "twitch-unichat-live",
      providerUserId: "user-lumapilot",
      preview: "privmsg twitch",
    },
  },
  {
    id: "m-002",
    platform: "kick",
    sourceMessageId: "kk-2001",
    sourceChannelId: "kick-xqc",
    sourceUserId: "user-reverbloop",
    author: "ReverbLoop",
    text: "Kick should appear in the mixed feed with a visible badge before the author line.",
    timestamp: "2026-03-23T12:08:00.000Z",
    badges: ["vip"],
    isSupporter: false,
    isOutgoing: false,
    isDeleted: false,
    canRenderInOverlay: true,
    actions: {
      reply: createMessageActionState(
        "reply",
        "disabled",
        "This channel is watch-only for replies."
      ),
      delete: createMessageActionState(
        "delete",
        "disabled",
        "This channel cannot delete messages."
      ),
    },
    rawPayload: {
      providerEvent: "chat.message",
      providerChannelId: "kick-xqc",
      providerUserId: "user-reverbloop",
      preview: "kick message",
    },
  },
  {
    id: "m-003",
    platform: "youtube",
    sourceMessageId: "yt-3001",
    sourceChannelId: "youtube-gamespot",
    sourceUserId: "user-novasynth",
    author: "NovaSynth",
    text: "YouTube can be typed and visible now even if the live connector ships later.",
    timestamp: "2026-03-23T12:07:00.000Z",
    badges: ["member"],
    isSupporter: true,
    isOutgoing: false,
    isDeleted: false,
    canRenderInOverlay: true,
    actions: {
      reply: createMessageActionState("reply", "available"),
      delete: createMessageActionState(
        "delete",
        "disabled",
        "This channel cannot delete messages."
      ),
    },
    rawPayload: {
      providerEvent: "liveChatMessage",
      providerChannelId: "youtube-gamespot",
      providerUserId: "user-novasynth",
      preview: "youtube live chat",
    },
  },
  {
    id: "m-004",
    platform: "twitch",
    sourceMessageId: "tw-1002",
    sourceChannelId: "twitch-shroud",
    sourceUserId: "user-echoharbor",
    author: "EchoHarbor",
    text: "Split view needs saved columns so the operator can reconnect one service without losing layout.",
    timestamp: "2026-03-23T12:05:00.000Z",
    badges: ["mod"],
    isSupporter: false,
    isOutgoing: false,
    isDeleted: false,
    canRenderInOverlay: true,
    actions: {
      reply: createMessageActionState("reply", "available"),
      delete: createMessageActionState("delete", "available"),
    },
    rawPayload: {
      providerEvent: "privmsg",
      providerChannelId: "twitch-shroud",
      providerUserId: "user-echoharbor",
      preview: "layout feedback",
    },
  },
  {
    id: "m-005",
    platform: "kick",
    sourceMessageId: "kk-2002",
    sourceChannelId: "kick-xqc",
    sourceUserId: "user-bytemango",
    author: "ByteMango",
    text: "Compact mode should keep moderation buttons reachable without taking over the whole row.",
    timestamp: "2026-03-23T12:04:00.000Z",
    badges: ["vip", "supporter"],
    isSupporter: true,
    isOutgoing: false,
    isDeleted: false,
    canRenderInOverlay: true,
    actions: {
      reply: createMessageActionState(
        "reply",
        "disabled",
        "This channel is watch-only for replies."
      ),
      delete: createMessageActionState(
        "delete",
        "disabled",
        "This channel cannot delete messages."
      ),
    },
    rawPayload: {
      providerEvent: "chat.message",
      providerChannelId: "kick-xqc",
      providerUserId: "user-bytemango",
      preview: "compact feedback",
    },
  },
  {
    id: "m-006",
    platform: "youtube",
    sourceMessageId: "yt-3002",
    sourceChannelId: "youtube-gamespot",
    sourceUserId: "user-roadmapghost",
    author: "RoadmapGhost",
    text: "Overlay should reuse the same normalized message objects instead of a separate format.",
    timestamp: "2026-03-23T12:02:00.000Z",
    badges: ["subscriber"],
    isSupporter: false,
    isOutgoing: false,
    isDeleted: false,
    canRenderInOverlay: true,
    actions: {
      reply: createMessageActionState("reply", "available"),
      delete: createMessageActionState(
        "delete",
        "disabled",
        "This channel cannot delete messages."
      ),
    },
    rawPayload: {
      providerEvent: "liveChatMessage",
      providerChannelId: "youtube-gamespot",
      providerUserId: "user-roadmapghost",
      preview: "overlay normalization",
    },
  },
  {
    id: "m-007",
    platform: "twitch",
    sourceMessageId: "tw-1003",
    sourceChannelId: "twitch-unichat-live",
    sourceUserId: "user-pixelwave",
    author: "PixelWave",
    text: "Chatterino-style split columns would be perfect for this!",
    timestamp: "2026-03-23T12:10:00.000Z",
    badges: ["subscriber"],
    isSupporter: false,
    isOutgoing: false,
    isDeleted: false,
    canRenderInOverlay: true,
    actions: {
      reply: createMessageActionState("reply", "available"),
      delete: createMessageActionState("delete", "available"),
    },
    rawPayload: {
      providerEvent: "privmsg",
      providerChannelId: "twitch-unichat-live",
      providerUserId: "user-pixelwave",
      preview: "chatterino style",
    },
  },
  {
    id: "m-008",
    platform: "twitch",
    sourceMessageId: "tw-1004",
    sourceChannelId: "twitch-shroud",
    sourceUserId: "user-quantumfox",
    author: "QuantumFox",
    text: "Just add the channel and it shows up in the column. Simple!",
    timestamp: "2026-03-23T12:11:00.000Z",
    badges: ["vip"],
    isSupporter: true,
    isOutgoing: false,
    isDeleted: false,
    canRenderInOverlay: true,
    actions: {
      reply: createMessageActionState("reply", "available"),
      delete: createMessageActionState("delete", "available"),
    },
    rawPayload: {
      providerEvent: "privmsg",
      providerChannelId: "twitch-shroud",
      providerUserId: "user-quantumfox",
      preview: "add channel",
    },
  },
  {
    id: "m-009",
    platform: "kick",
    sourceMessageId: "kk-2003",
    sourceChannelId: "kick-xqc",
    sourceUserId: "user-voidranger",
    author: "VoidRanger",
    text: "The new compact layout is so clean! Love the icon buttons.",
    timestamp: "2026-03-23T12:12:00.000Z",
    badges: ["mod"],
    isSupporter: false,
    isOutgoing: false,
    isDeleted: false,
    canRenderInOverlay: true,
    actions: {
      reply: createMessageActionState(
        "reply",
        "disabled",
        "This channel is watch-only for replies."
      ),
      delete: createMessageActionState(
        "delete",
        "disabled",
        "This channel cannot delete messages."
      ),
    },
    rawPayload: {
      providerEvent: "chat.message",
      providerChannelId: "kick-xqc",
      providerUserId: "user-voidranger",
      preview: "layout praise",
    },
  },
  {
    id: "m-010",
    platform: "youtube",
    sourceMessageId: "yt-3003",
    sourceChannelId: "youtube-gamespot",
    sourceUserId: "user-stardust",
    author: "StarDust",
    text: "Having all chats in one place makes moderation so much easier!",
    timestamp: "2026-03-23T12:13:00.000Z",
    badges: ["member", "supporter"],
    isSupporter: true,
    isOutgoing: false,
    isDeleted: false,
    canRenderInOverlay: true,
    actions: {
      reply: createMessageActionState("reply", "available"),
      delete: createMessageActionState(
        "delete",
        "disabled",
        "This channel cannot delete messages."
      ),
    },
    rawPayload: {
      providerEvent: "liveChatMessage",
      providerChannelId: "youtube-gamespot",
      providerUserId: "user-stardust",
      preview: "moderation tools",
    },
  },
  {
    id: "m-011",
    platform: "twitch",
    sourceMessageId: "tw-1005",
    sourceChannelId: "twitch-unichat-live",
    sourceUserId: "user-cosmicdev",
    author: "CosmicDev",
    text: "When is the Tauri backend going to support real IRC connections?",
    timestamp: "2026-03-23T12:14:00.000Z",
    badges: ["vip"],
    isSupporter: false,
    isOutgoing: false,
    isDeleted: false,
    canRenderInOverlay: true,
    actions: {
      reply: createMessageActionState("reply", "available"),
      delete: createMessageActionState("delete", "available"),
    },
    rawPayload: {
      providerEvent: "privmsg",
      providerChannelId: "twitch-unichat-live",
      providerUserId: "user-cosmicdev",
      preview: "backend question",
    },
  },
  {
    id: "m-012",
    platform: "twitch",
    sourceMessageId: "tw-1006",
    sourceChannelId: "twitch-unichat-live",
    sourceUserId: "user-you",
    author: "You",
    text: "Working on it! The foundation is laid out, just need to wire up the actual providers.",
    timestamp: "2026-03-23T12:15:00.000Z",
    badges: ["broadcaster", "operator"],
    isSupporter: false,
    isOutgoing: true,
    isDeleted: false,
    canRenderInOverlay: true,
    actions: {
      reply: createMessageActionState("reply", "disabled", "Cannot reply to own message"),
      delete: createMessageActionState("delete", "available"),
    },
    rawPayload: {
      providerEvent: "privmsg",
      providerChannelId: "twitch-unichat-live",
      providerUserId: "user-you",
      preview: "dev update",
    },
  },
  {
    id: "m-013",
    platform: "twitch",
    sourceMessageId: "tw-1007",
    sourceChannelId: "twitch-unichat-live",
    sourceUserId: "user-neonblade",
    author: "NeonBlade",
    text: "This split view is exactly what I needed for managing multiple streams!",
    timestamp: "2026-03-23T12:16:00.000Z",
    badges: ["subscriber"],
    isSupporter: true,
    isOutgoing: false,
    isDeleted: false,
    canRenderInOverlay: true,
    actions: {
      reply: createMessageActionState("reply", "available"),
      delete: createMessageActionState("delete", "available"),
    },
    rawPayload: {
      providerEvent: "privmsg",
      providerChannelId: "twitch-unichat-live",
      providerUserId: "user-neonblade",
      preview: "split view feedback",
    },
  },
  {
    id: "m-014",
    platform: "twitch",
    sourceMessageId: "tw-1008",
    sourceChannelId: "twitch-shroud",
    sourceUserId: "user-ironforge",
    author: "IronForge",
    text: "Shroud's aim is still insane after all these years",
    timestamp: "2026-03-23T12:17:00.000Z",
    badges: ["vip", "supporter"],
    isSupporter: true,
    isOutgoing: false,
    isDeleted: false,
    canRenderInOverlay: true,
    actions: {
      reply: createMessageActionState("reply", "available"),
      delete: createMessageActionState("delete", "available"),
    },
    rawPayload: {
      providerEvent: "privmsg",
      providerChannelId: "twitch-shroud",
      providerUserId: "user-ironforge",
      preview: "shroud aim",
    },
  },
  {
    id: "m-015",
    platform: "kick",
    sourceMessageId: "kk-2004",
    sourceChannelId: "kick-xqc",
    sourceUserId: "user-shadowstrike",
    author: "ShadowStrike",
    text: "xQc reacting to old clips is always entertaining",
    timestamp: "2026-03-23T12:18:00.000Z",
    badges: ["mod"],
    isSupporter: false,
    isOutgoing: false,
    isDeleted: false,
    canRenderInOverlay: true,
    actions: {
      reply: createMessageActionState(
        "reply",
        "disabled",
        "This channel is watch-only for replies."
      ),
      delete: createMessageActionState(
        "delete",
        "disabled",
        "This channel cannot delete messages."
      ),
    },
    rawPayload: {
      providerEvent: "chat.message",
      providerChannelId: "kick-xqc",
      providerUserId: "user-shadowstrike",
      preview: "xqc clips",
    },
  },
  {
    id: "m-016",
    platform: "kick",
    sourceMessageId: "kk-2005",
    sourceChannelId: "kick-xqc",
    sourceUserId: "user-crimsonwave",
    author: "CrimsonWave",
    text: "OMEGALUL",
    timestamp: "2026-03-23T12:19:00.000Z",
    badges: [],
    isSupporter: false,
    isOutgoing: false,
    isDeleted: false,
    canRenderInOverlay: true,
    actions: {
      reply: createMessageActionState(
        "reply",
        "disabled",
        "This channel is watch-only for replies."
      ),
      delete: createMessageActionState(
        "delete",
        "disabled",
        "This channel cannot delete messages."
      ),
    },
    rawPayload: {
      providerEvent: "chat.message",
      providerChannelId: "kick-xqc",
      providerUserId: "user-crimsonwave",
      preview: "omegalul",
    },
  },
  {
    id: "m-017",
    platform: "youtube",
    sourceMessageId: "yt-3004",
    sourceChannelId: "youtube-gamespot",
    sourceUserId: "user-velociraptor",
    author: "VelociRaptor",
    text: "GameSpot's retro reviews are pure nostalgia",
    timestamp: "2026-03-23T12:20:00.000Z",
    badges: ["member"],
    isSupporter: false,
    isOutgoing: false,
    isDeleted: false,
    canRenderInOverlay: true,
    actions: {
      reply: createMessageActionState("reply", "available"),
      delete: createMessageActionState(
        "delete",
        "disabled",
        "This channel cannot delete messages."
      ),
    },
    rawPayload: {
      providerEvent: "liveChatMessage",
      providerChannelId: "youtube-gamespot",
      providerUserId: "user-velociraptor",
      preview: "retro reviews",
    },
  },
  {
    id: "m-018",
    platform: "youtube",
    sourceMessageId: "yt-3005",
    sourceChannelId: "youtube-gamespot",
    sourceUserId: "user-thunderbolt",
    author: "ThunderBolt",
    text: "Anyone else here since the first upload?",
    timestamp: "2026-03-23T12:21:00.000Z",
    badges: ["member", "supporter"],
    isSupporter: true,
    isOutgoing: false,
    isDeleted: false,
    canRenderInOverlay: true,
    actions: {
      reply: createMessageActionState("reply", "available"),
      delete: createMessageActionState(
        "delete",
        "disabled",
        "This channel cannot delete messages."
      ),
    },
    rawPayload: {
      providerEvent: "liveChatMessage",
      providerChannelId: "youtube-gamespot",
      providerUserId: "user-thunderbolt",
      preview: "first viewer",
    },
  },
  {
    id: "m-019",
    platform: "twitch",
    sourceMessageId: "tw-1009",
    sourceChannelId: "twitch-shroud",
    sourceUserId: "user-phoenixrise",
    author: "PhoenixRise",
    text: "That clutch play was insane!",
    timestamp: "2026-03-23T12:22:00.000Z",
    badges: ["subscriber"],
    isSupporter: false,
    isOutgoing: false,
    isDeleted: false,
    canRenderInOverlay: true,
    actions: {
      reply: createMessageActionState("reply", "available"),
      delete: createMessageActionState("delete", "available"),
    },
    rawPayload: {
      providerEvent: "privmsg",
      providerChannelId: "twitch-shroud",
      providerUserId: "user-phoenixrise",
      preview: "clutch play",
    },
  },
  {
    id: "m-020",
    platform: "twitch",
    sourceMessageId: "tw-1010",
    sourceChannelId: "twitch-unichat-live",
    sourceUserId: "user-mysticarrow",
    author: "MysticArrow",
    text: "Can we get a tutorial on setting this up?",
    timestamp: "2026-03-23T12:23:00.000Z",
    badges: ["vip"],
    isSupporter: false,
    isOutgoing: false,
    isDeleted: false,
    canRenderInOverlay: true,
    actions: {
      reply: createMessageActionState("reply", "available"),
      delete: createMessageActionState("delete", "available"),
    },
    rawPayload: {
      providerEvent: "privmsg",
      providerChannelId: "twitch-unichat-live",
      providerUserId: "user-mysticarrow",
      preview: "tutorial request",
    },
  },
  {
    id: "m-021",
    platform: "kick",
    sourceMessageId: "kk-2006",
    sourceChannelId: "kick-xqc",
    sourceUserId: "user-frostbyte",
    author: "FrostByte",
    text: "Chat moving so fast I can't keep up",
    timestamp: "2026-03-23T12:24:00.000Z",
    badges: ["subscriber"],
    isSupporter: false,
    isOutgoing: false,
    isDeleted: false,
    canRenderInOverlay: true,
    actions: {
      reply: createMessageActionState(
        "reply",
        "disabled",
        "This channel is watch-only for replies."
      ),
      delete: createMessageActionState(
        "delete",
        "disabled",
        "This channel cannot delete messages."
      ),
    },
    rawPayload: {
      providerEvent: "chat.message",
      providerChannelId: "kick-xqc",
      providerUserId: "user-frostbyte",
      preview: "fast chat",
    },
  },
  {
    id: "m-022",
    platform: "youtube",
    sourceMessageId: "yt-3006",
    sourceChannelId: "youtube-gamespot",
    sourceUserId: "user-silverfang",
    author: "SilverFang",
    text: "The production quality on this stream is top tier",
    timestamp: "2026-03-23T12:25:00.000Z",
    badges: ["member"],
    isSupporter: true,
    isOutgoing: false,
    isDeleted: false,
    canRenderInOverlay: true,
    actions: {
      reply: createMessageActionState("reply", "available"),
      delete: createMessageActionState(
        "delete",
        "disabled",
        "This channel cannot delete messages."
      ),
    },
    rawPayload: {
      providerEvent: "liveChatMessage",
      providerChannelId: "youtube-gamespot",
      providerUserId: "user-silverfang",
      preview: "production quality",
    },
  },
];

export const mockWidgets: WidgetConfig[] = [
  {
    id: "widget-main",
    name: "Main Stage",
    status: "live",
    filter: "all",
    sceneHint: "Studio A browser source",
    themeHint: "Aurora glass",
    port: 1421,
  },
  {
    id: "widget-supporters",
    name: "Supporter Lens",
    status: "draft",
    filter: "supporters",
    sceneHint: "Sponsor break scene",
    themeHint: "Champagne pulse",
    port: 1421,
  },
];
