// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Platform } from "./Platform";

export type AuthStatus = { platform: Platform, isConnected: boolean, username: string | null, expiresAt: string | null, };