// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatAccountCreate = { platform: string, username: string, userId: string, avatarUrl: string | null, authStatus: string | null, accessToken: string | null, refreshToken: string | null, tokenExpiresAt: string | null, };