// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CustomEmote = { id: string | null, platform: string, channelId: string | null, emoteCode: string, emoteUrl: string, emoteType: string, createdAt: string | null, updatedAt: string | null, deletedAt: string | null, };