// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Badge } from "./Badge";
import type { Emote } from "./Emote";

export type IrcMessage = { id: string, platform: string, channelId: string, channelName: string, author: string, authorId: string, text: string, timestamp: bigint, badges: Array<Badge>, color: string, emotes: Array<Emote>, isMod: boolean, isSubscriber: boolean, isHighlighted: boolean, };