// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverlaySource } from "./OverlaySource";

export type OverlayConfig = { port: number, enabled: boolean, sources: Array<OverlaySource>, };